### ISSUE TITLE
Settings tab for the plugin does not appear

### ISSUE THREAD

**Issue by chrisgrieser** [Mocca101/obsidian-plugin-groups#1]
I just installed the plugin via BRAT, and after installation, enabling, and also restarting Obsidian, the settings tab for the plugin does not seem to appear? 

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/73286100/209188037-51e83806-888b-4716-811e-474557c026bb.png">

**Comment by Mocca101** [comment]
Thanks for the Issue I'll look into it!

**Comment by imeed166** [comment]
I'm having the same issue.

**Comment by Lisandra-dev** [comment]
Same issue on my side !

**Comment by Mocca101** [comment]
Yes sorry for the inconvenience! It should be fixed with the new release, please check and let me know if it works. Thanks for the feedback and patience.

**Comment by Mocca101** [comment]
Closing it as the issue didn't appear again with the new releas and further testing. Just comment if it occures again.
