### ISSUE TITLE
Please Add Option To Disable Plugins On Startup Like Enable Plugin On Startup

### ISSUE THREAD

**Issue by paranjay245** [Mocca101/obsidian-plugin-groups#10]
It Would Be Really Helpful Thank you soo much for Awesome Plugin :)

**Comment by Lisandra-dev** [comment]
The update 1.2.0 add this option :D

**Comment by paranjay245** [comment]
oh damn thank you soo much it just released today damn thank you soo much man :) @Lisandra-dev
