### ISSUE TITLE
[BUG] Slider number for delay doesn't update when moved

### ISSUE THREAD

**Issue by Lisandra-dev** [Mocca101/obsidian-plugin-groups#11]
Hello!
Bug I spotted using the 1.2.0 : The slider number doesn't update when moved. It goes updated after saving, forcing to "try & error" to get the right number.

See the video here : 

https://user-images.githubusercontent.com/30244939/210130034-05de7313-1e2f-4a61-aa90-f43246df14bc.mp4

**Comment by Mocca101** [comment]
Good find, thank you. It should be fixed now in [1.2.1](https://github.com/Mocca101/obsidian-plugin-groups/releases/tag/1.2.1)
