### ISSUE TITLE
[Bug]: Repeat loading the same plugin

### ISSUE THREAD

**Issue by hustrjh** [Mocca101/obsidian-plugin-groups#13]
## Bug
I created 2 plugin groups which are loaded on startup with different delay time. The two groups all contain **`Quick Explorer`**. Then **`Quick Explorer`** will be loaded twice. It is my mistake to include **`Quick Explorer`** in both groups. But it's not good to load the same plugin twice.

![image](https://user-images.githubusercontent.com/69783980/210676129-71d91b12-a843-466f-99ac-b3892ba93e83.png)

## Suggestion
Maybe it's better to check the plugins which are loaded on startup and to remove the redundant plugins.
PS: Enable the same group twice by the **`plugin groups`** will not load the same plugin again.

**Comment by Mocca101** [comment]
Thanks for bringing this to my attention I'll look into it!

**Comment by Mocca101** [comment]
Should be fixed in 1.3.0 if not, do let me know!

**Comment by hustrjh** [comment]
Fantastic! It works well. By the way I love your design of UI. :+1:

**Comment by Mocca101** [comment]
Glad to hear it! 🎉
