### ISSUE TITLE
[BUG] Plugin stops working / becomes disabled after closing and opening Obsidian

### ISSUE THREAD

**Issue by MSBack** [Mocca101/obsidian-plugin-groups#20]
I have set up a few plugin groups for delaying the upstart of certain plugins. This works, but after I close and open Obsidian one or two times, the Plugin Groups plugin becomes disabled and all the plugins start without delay again. 

The strange thing is that the toggle to disable Plugin Groups under community plugins stays as enabled. Nevertheless, the settings page for Plugin Groups disappears, and like I said, all plugins run from startup without delay, so the plugin stops working.

By disabling and enabling Plugin Groups on the community plugins page, I can re-enable the Plugin groups plugin so its settings page reappears, and it starts working again, for a while.

I don't know if this is relevant, but anyway, I installed the plugin using BRAT – not manually.

**Comment by Mocca101** [comment]
Thanks a lot for letting me know, that definitely shouldn't happen! 

I do have a suspicion where the problem might lie, but I'd need a bit more information to tackle this problem properly, as this has never happened for me.

First of, please don't disclose any information that might be private and only as much as you are comfortable with!

Now:
1. Do you have the plugin itself (plugin groups) in a group?
2. What plugins do you have in the 'community-plugins.json'
3. Did it happen multiple times and if yes did you notice any specific things you did when it got disabled? 
4. Have you checked the console (ctrl+shift+i)? Did it say anything? If not it would be very helpful if you could check that the next time it happens!

**Comment by MSBack** [comment]
Thanks for the quick response. 

1. No, the plugin itself is not in any group, because I cannot find it within the settings when editing groups. Therefore, even if I wanted to, I wouldn't be able to add Plugin Groups to a group. Is that by design?
2. For some reason, although I have 95 installed, of which 87 are enabled (yeah, too many, I know), these are the only ones listed in community-plugins.json:

```
[
  "templater-obsidian",
  "periodic-notes",
  "tag-wrangler",
  "obsidian-sortable",
  "obsidian-style-settings",
  "obsidian-smart-typography",
  "table-editor-obsidian",
  "better-word-count",
  "calendar",
  "dataview",
  "file-explorer-note-count",
  "obsidian-linter",
  "note-refactor-obsidian",
  "pane-relief",
  "recent-files-obsidian",
  "cm-typewriter-scroll-obsidian",
  "obsidian-hover-editor",
  "obsidian-word-sprint",
  "obsidian-advanced-uri",
  "editing-toolbar",
  "obsidian-completr",
  "obsidian-gallery",
  "obsidian-projects",
  "obsidian-plugin-update-tracker",
  "open-gate",
  "obsidian-text-format",
  "open-related-url",
  "cmdr",
  "longform",
  "hard-breaks",
  "chord-lyrics",
  "obsidian-icon-folder"
]
```
I closed Obsidian, deleted the community-plugins.json file, and now it regenerated the file with the all the plugins listed.
3. I haven't noticed anything specific, other than closing and reopening Obsidian, where after the plugin would not work and have no settings.
4. Yes, I just checked, and I get this error message in the console:
```
plugin:obsidian-plugin-groups:134 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'plugins')
    at _PluginManager.getInstalledPluginFromId (plugin:obsidian-plugin-groups:134:34)
    at eval (plugin:obsidian-plugin-groups:98:43)
    at Set.forEach (<anonymous>)
    at eval (plugin:obsidian-plugin-groups:97:22)
    at Map.forEach (<anonymous>)
    at _PluginManager.loadNewPlugins (plugin:obsidian-plugin-groups:95:39)
    at PgMain.onload (plugin:obsidian-plugin-groups:1413:19)
```

**Comment by MSBack** [comment]
The error message came after starting Obsidian, and nothing else.

**Comment by MSBack** [comment]
No problem! Great, looking forward to it!

Yeah, I have the latest version (v1.1.9).

**Comment by Mocca101** [comment]
Perfect thanks!
