### ISSUE TITLE
Compatibility with other plugins that check `app.plugins.enabledPlugins` for certain plugin dependencies

### ISSUE THREAD

**Issue by Profile8647** [Mocca101/obsidian-plugin-groups#24]
Some plugins, such as [marcusolsson/obsidian-projects](https://github.com/marcusolsson/obsidian-projects), make use of Dataview and, to do so, `app.plugins.enabledPlugins` is checked for the `dataview` entry. 

I opened a feature request with that project to check `app.plugins.plugins['dataview']?._loaded` instead ([FR: Support Mocca101/obsidian-plugin-groups with Dataview queries #448](https://github.com/marcusolsson/obsidian-projects/issues/448)), however I think it would more appropriate for your plugin to use `app.plugins.enabledPlugins.add(...)` for plugins your project loads as that is the expected default behavior compatible with the `app.plugins.enabledPlugins` method.

Similarly, if you unload a plugin with your project, I would suggest using `app.plugins.enabledPlugins.delete(...)`.

Thank you!

**Comment by Mocca101** [comment]
Thanks for looking into this!
Unfortunately that is not possible, as adding plugins via `app.plugins.enabledPlugins.add(...)` causes them to be loaded by obsidian, canceling out the effectiveness of the delayed startup, one of the core features of plugin groups.

Maybe it's somehow possible to hijack checks for enabled plugins, returning the ones enabled via plugin groups but I do not know how that might work at the moment and unfortunately won't be able to look into it in the forseeable future. 

I'll leave this issue open in case anyone has any ideas or wants to try fixing/implementing this.

**Comment by Profile8647** [comment]
No problem! Thank you for responding and for looking into my request.

I can't reproduce what you are describing. Are you certain about your claim that app.plugins.enabledPlugins.add(...) causes a plugin to load? As far as I understand, `app.plugins.enabledPlugins.add(...)` is only populating a set stored in memory. I verified that the method does not update the `community-plugins.json` file between reloads as well. Disabling your plugin, reloading and using `app.plugins.enabledPlugins.add('dataview')` does not appear to have loaded Dataview for me in a sandbox vault on Windows 11.

Here's a screen recording of my observations:  https://user-images.githubusercontent.com/125712365/223916251-61a57d5d-c399-483f-8b04-5020883d7119.mp4

Unless I'm mistaken, you could presumably call app.plugins.enabledPlugins.add(...) after your plugin loads another even if it's delayed and the set wouldn't carry over between app reloads.

**Comment by Mocca101** [comment]
In my tests it did, but I might have missed something. 
In case you want to take a look at it, I added  `app.plugins.enabledPlugins.add(...) ` and disable at [enablePlugin](https://github.com/Mocca101/obsidian-plugin-groups/blob/07b3df8e9b2644f3e7bb5f352b08eba602f0a613/src/Managers/PluginManager.ts#L156) and [disablePlugin](https://github.com/Mocca101/obsidian-plugin-groups/blob/07b3df8e9b2644f3e7bb5f352b08eba602f0a613/src/Managers/PluginManager.ts#L162) respectively after first en/disabling the plugin via `app.plugins.enablePlugin(...)` (and before returning the success.

I'll try to look into it further in the future otherwise.

**Comment by Profile8647** [comment]
Thanks for the helpful suggestion about where to insert the functionality. I think I figured the issue out and a solution to resolve it.

Per your guidance, I modified [`enablePlugin(...)`](https://github.com/Mocca101/obsidian-plugin-groups/blob/07b3df8e9b2644f3e7bb5f352b08eba602f0a613/src/Managers/PluginManager.ts#L156) and [`disablePlugin(...)`](https://github.com/Mocca101/obsidian-plugin-groups/blob/07b3df8e9b2644f3e7bb5f352b08eba602f0a613/src/Managers/PluginManager.ts#L162) respectively to:

```typescript
	private static enablePlugin(plugin: PgPlugin): Promise<boolean> {
		const enablePluginResult =
			Manager.getInstance().obsidianPluginsObject.enablePlugin(plugin.id);

		if (enablePluginResult) {
			Manager.getInstance().obsidianPluginsObject.enabledPlugins.add(
				plugin.id
			);
		}
		return enablePluginResult;
	}

	private static disablePlugin(plugin: PgPlugin) {
		const disablePluginResult =
			Manager.getInstance().obsidianPluginsObject.disablePlugin(
				plugin.id
			);

		if (disablePluginResult) {
			Manager.getInstance().obsidianPluginsObject.enabledPlugins.delete(
				plugin.id
			);
		}
		return disablePluginResult;
	}
```

And while that did achieve the functionality I was looking for, I also encounter the issue you described in [your initial reply](https://github.com/Mocca101/obsidian-plugin-groups/issues/24#issuecomment-1460965197) when I unload your plugin, after it had loaded plugins; at unload, the plugins that obsidian-plugin-groups loaded were then added to `community-plugins.json` so they became 'permanently enabled'.

It seems that Obsidian updates the `community-plugins.json` file with the remaining entries of the `app.plugins.enabledPlugins`  set whenever `app.plugins.disablePlugin(...)` is called. However, I did not observe this issue when [`disable()`](https://github.com/Mocca101/obsidian-plugin-groups/blob/07b3df8e9b2644f3e7bb5f352b08eba602f0a613/src/DataStructures/PluginGroup.ts#L112) was called. So, the simple fix seemed to be an implementation of that function for all groups in [`onunload()`](https://github.com/Mocca101/obsidian-plugin-groups/blob/07b3df8e9b2644f3e7bb5f352b08eba602f0a613/main.ts#L98):

```typescript
	onunload() {
		Manager.getInstance().groupsMap.forEach((group) => {
			group.disable();
		});
	}
```

After adding that, the unwanted behavior went away.

Feel free to copy that into your dev environment or please let me know if you would rather I submit a PR.

Thanks!

**Comment by Mocca101** [comment]
Hey, thanks a lot for all the work you put into this. Even if it turned out differently then initially expected, I really appreciate it and can actually use the Obsidian Dev's suggestion as well!

**Comment by Profile8647** [comment]
No problem! I was happy to spend my time on it and learn a bit more, myself.
