### ISSUE TITLE
No commands to turn plugin groups on and off in the command palette.

### ISSUE THREAD

**Issue by YousufSSyed** [Mocca101/obsidian-plugin-groups#29]
I reinstalled Plugin Groups, created a new group and still didn't see any commands for it in the palette. I also did tried this on another vault and it didn't work.

While you're at it, I want you to look at my other feature request: [A command to Toggle (not just turn on or off) plugin groups](https://github.com/Mocca101/obsidian-plugin-groups/issues/28).

**Comment by Mocca101** [comment]
Could you make sure that you've turned on commands for plugin groups globally in the plugins general settings? 

![58677062-3ed3-4b78-af16-c846f17abf83.png](https://user-images.githubusercontent.com/49754596/229499110-ff37ab41-3f2c-4ef3-9278-8eb37ca0ca4a.png)

**Comment by YousufSSyed** [comment]
Oh I didn't notice that. I thought it would happen automatically. I made this feature request: [Add a default settings section, to apply default settings to new plugin groups](https://github.com/Mocca101/obsidian-plugin-groups/issues/31).
