### ISSUE TITLE
Option to add newly installed plugins automatically to a group

### ISSUE THREAD

**Issue by imeed166** [Mocca101/obsidian-plugin-groups#3]
I've been using tfthacker templater script to delay loading plugins on startup, but I stopped using it because I'm always trying new plugins and having to manually add each newly installed plugin to the list was a pain. 

I wonder if you could add a toggle to a group that says "add newly installed plugins to this group". 

**The use case:** If, for example, I have one group that is opened on startup delayed by 3 seconds. the new plugins would be added automatically instead of manually adding them each time.

The new plugins can be installed with the official plugin store or with BRAT, it would be nice if this feature handles both ways of installing plugins.

**Comment by Mocca101** [comment]
Good Ideas, I'll try to get it to work.
Does anyone know if there is an event or something like that, when a new plugin is added to obsidian?

**Comment by Mocca101** [comment]
In Release 1.2.0
