### ISSUE TITLE
FR: Toggle for short notifications

### ISSUE THREAD

**Issue by decatetsu** [Mocca101/obsidian-plugin-groups#5]
On mobile, I want to be notified about loading of group, but I don't want to see list of plugins, I want to get only group name. So it'd be nice to have a checkbox or toggle for short version of notifications.

In other words, ability to remove data in red square.

![Image](https://user-images.githubusercontent.com/56955307/209640606-a13b5e5a-1a9d-403e-854a-913d19b7c388.png)

**Comment by Mocca101** [comment]
Good idea, should be in the next release.

**Comment by Mocca101** [comment]
In Release 1.2.0
