### ISSUE TITLE
[FR] Allow to sort the plugin list

### ISSUE THREAD

**Issue by Lisandra-dev** [Mocca101/obsidian-plugin-groups#6]
I would to love to have a way to sort the plugin list by the other group.

For example, I created a group X with some plugin. I create a new group, and in the plugin's list, I would to remove all plugin that are already in the list X.
So, I get a clean list!

---

Also, a way to hide all plugin that are already checked, so I can see all plugin not in the group.

**Comment by Mocca101** [comment]
I'll look into it!
A bit of a rework for the UI/UX  is planned and it might be a good opportunity to include this there.
For clarification: You mean something like filtering the plugins by the ones existing in other groups?

**Comment by imeed166** [comment]
I agree with @Lisandra-dev. When creating a new group, I expect to see only the plugins that don't belong to any group.

Maybe add a toggle in global settings that says "plugins can only belong to one group at a time".

**Comment by Lisandra-dev** [comment]
> I'll look into it! A bit of a rework for the UI/UX is planned and it might be a good opportunity to include this there. For clarification: You mean something like filtering the plugins by the ones existing in other groups?

exactly!

**Comment by Mocca101** [comment]
It's now in 1.3.0 if there's further functionality related to this, please open a new issues with a reference to this!
