### ISSUE TITLE
[FR] Allow to disable plugin 

### ISSUE THREAD

**Issue by Lisandra-dev** [Mocca101/obsidian-plugin-groups#7]
Sometimes, I load plugin only for debugging purpose, and forgot to remove them. I would like to have a way to create a startup plugin group that **disable** plugin.

With my old Fast-Start script, I do that with `await plugin.app.plugins.disablePlugin(plugin)`

**Comment by Mocca101** [comment]
Good idea!

**Comment by Mocca101** [comment]
In Release 1.2.0
